### PR TITLE
Major code cleanup and update

### PR DESCRIPTION
**Pull request by mensfeld**
* jruby support drop - there's no 2.0 syntax for jruby yet. Once it's out of beta - no further work needs to be done (works for me on beta)
* drop 1.8 and 1.9 - even ruby guys recommend upgrading
* added rubocop for spec/, examples/ and benchmarks/
* fixed examples issues (they were not working anymore)
* fixed benchmarks (outdated libs, etc)
* added examples execution to rspec - now rspec will notify if any example is not working. That way we will be able to provide code changes without having to worry that they will break examples
* added way more specs (93% code coverage)
* added rubocop to travis
* some minor cleanups
* moved from rvmrc (deprecated) to ruby-gemset and ruby-version
* removed unused gems
* added simplecov to track code coverage
* updated syntax to match 2.2.2
* moved versioning to Aspector::VERSION
* gemspec cleanup
* benchmarks now use RubyProf new version
* benchmarks moved to /benchmarks
* all the examples work again
* lib/aspector load order rearrange
* aspector advice rearrange - now it doesn't have to use integer values with constants
* before_filter as a separate TYPE - that way we don't have to "if" anything - works out of the box easier
* some method optimization or rewrites for many methods - works the same, looks way better
* advices metadata cleanup - no need for mandatory_options anymore
* API CHANGE: old_methods_only replaced with existing_methods_only - when I started to use aspector the "old" was hard to understand - existing is way more straightforward
* base disabled? now returns either true or false (no nil since it might change)
* boolean methods that return nil return now true/false
* before advices are now picked from before and before_filter advices
* METHOD_TEMPLATE update with new logger logic
* METHOD_TEMPLATE indentations are now more readable
* base_class_methods now generate all the bind methods automatically based on Aspector::Advice::TYPES
* deferred options to_s cleanup
* New logger that is based on Ruby default logger (::Logger) - same log levels, same API (except *args for our contextes)
* Logger is now much smaller
* Logging - constanize is now easier to read but the API stays the same (fallback as well)
* Method matcher#to_s uses now the & syntax for inspect
* ObjectExtension #returns removed - it was never used (throw was never used)
* Spec helper cleanup
* Rspec no longer needs monkey patching (config.disable_monkey_patching!)
* Class building logic is now wrapped in a module instead of a single method - all the class "building" and "cloning" happens in one place
* Added some pendings for future improvement
* skip_if_false for a before that should act as before_filter removed (since before filter is now a separate aspect)
* version dump

I think that's all ;)

### CODE REVIEW

**Comment by gcao** [comment]
I think we should still support 1.9, even though it's end of life officially. As far as I know, there is nothing special we need to do to support it.

**Comment by mensfeld** [comment]
@gcao there is - there are many syntax incompatibilities between 1.9.3 and 2.0 (and we're already at 2.2.2) like keyword arguments that I'm planning to add to aspector, symbol array literals (%i) that I've used. Also - this is just a first step - it seems that we could use Module#prepend (added in 2.0.0) to generate all the aspector code instead of building with ERB. The same goes for unbound methods that we could use. Also const_get understands namespaces (that is used in this branch as well). Ah and logger is compatibile with syslog

**Comment by gcao** [comment]
Cool. I'll merge it. Feel free to commit and merge your changes to master in the future. I'll take the back seat from now  on. ;-)

**Comment by mensfeld** [comment]
You still need to release a new version to rubygems once there's something "really" new to release - in terms of performance or the way the code works. Now there are just many cleanups and optimisations.

**Comment by gcao** [comment]
No problem. I'll do it whenever it's needed. Please add your name to contributors in README and authors in gemspec.

**Comment by mensfeld** [comment]
Thanks! Will do that with a README update that I'm preparing. After that I will look into the exp branch.

Btw do we the rest of the branches (except master and exp)?

**Comment by gcao** [comment]
I would like to keep the old branches around unless it's totally no use. Give me some time, I'll rename them with a prefix like OLD_

**Comment by mensfeld** [comment]
No rush - I won't touch any of them.

**Pull request merged**
